### ISSUE TITLE
Golang port

### ISSUE THREAD

**Issue by netgusto** [r3mi/poly2tri.js#9]
I just made a golang port of the library : https://github.com/netgusto/poly2tri-go
It's a 1:1 port of version 1.5.0; the test suite is not ported yet.

BSD 3-clause New License states this :

> prohibits others from using the name of the project or its contributors to promote derived products without written consent.

So I just wanted to know if you consent to this port ?
Thanks !

**Comment by r3mi** [comment]
Thanks for the news.
No problem on my side ! But you should ask the original authors of [poly2tri](https://github.com/greenm01/poly2tri) :-)

- Mason Green @greenm01 (C++ version, from which poly2tri.js was derived)
- Thomas Åhlén (Java version)

They have selected the BSD licence. I know they have always been happy to see additional ports !

**Comment by netgusto** [comment]
> No problem on my side !

Great :)

>  You should ask the original authors of poly2tri 

I will do that.

Thanks !
